### ISSUE TITLE
Confusion in regards to type of respondable function

### ISSUE THREAD

**Issue by DanielAndersen** [MerlinLabs/respondable#17] opened 2018-05-04 12:29 UTC
When looking at your types.js file it is clear that the function `respondable` takes an object and a function of type `onChangeCb` as the first two arguments.

`onChangeCb` is defined as: 
```
type onChangeCb = (
  matches: Array<string|void>,
  priority: string|void,
  ...rest: Array<void>
) => void;
```

Though when the respondable package is used in your 'styled-react-components' package (which is excellent by the way), the function `setScreenSize` (in ScreenSizeContext.js) has the signature:
(string, string) => void

Is there a bug in the type specified, or is it a matter of FlowType not being as strict?

(I am using TypeScript, and have defined types deducted from your FlowTypes)

**Comment by DanielAndersen** [comment] 2018-05-07 08:48
It was the JSDoc on setScreenSize that threw me off, it seems that the type of `active` is wrongly specified as string instead of Array<string>:

/**
   * setScreenSize
   *
   * this method is a thin wrapper around setState for setting
   * the appropriate screenSizes into the context state. This is
   * used as the respondable callback method. Anytime screensize
   * changes this method will be called.
   *
   * Note: we use largest instead of active prop as active because
   * media queries defined in userland might be competing. Respondable
   * api always provides the largest param even if queries do not
   * compete. largest is the largest active screenSize.
   *
   * @param {String} active  current active screenSize
   * @param {String} largest largest of active screenSizes if any compete
   */

**Comment by Nathan-Schwartz** [comment] 2018-05-07 15:47
Nice catch @DanielAndersen 👍 

Are you comfortable closing this? It seems the issue is in the styled-material-components repo.

**Closed** 2018-05-09 08:25 UTC
